version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sb-portal-web-dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/app               # Editas en VS Code y se refleja
      - /app/node_modules    # Evita pisar node_modules del contenedor
