FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=development
# Para que Next/Turbopack detecte cambios en bind mounts (Win/Mac)
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

COPY package*.json ./
RUN npm ci

# Copiamos el código (luego el volume lo sobreescribe en runtime)
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
